### ISSUE TITLE
TODO: Documentation for upcoming v1.0.0 release

### ISSUE THREAD

**Issue by caffeine-addictt** [python-thread/thread.ngjx.org#16]
# Feature Request
Your issue may already be reported!
Please check out our [active issues](https://github.com/python-thread/thread.ngjx.org/issues) before creating one.

## Scope
Documentation should be cover **all** the features in `thread`

## Describe the Solution You'd Like

- [x] Documentation for `Thread()`
- [x] Documentation for `ParallelProcessing()`
- [x] Documentation for decorators
- [x] Documentations for exceptions
- [x] Documentation for configuration
- [x] Documentation for CLI
- [x] Introduction page
- [x] Documentation for installation
- [x] Root page
- [x] About page
- [x] SEO

## Additional Context

- [x] Updated thread [README.md](https://github.com/python-thread/thread/blob/main/README.md) to redirect documentation to [thread.ngjx.org](thread.ngjx.org)
